---
- hosts: ci-node
  tasks:
    - name: Install requirements
      become: yes
      package:
        name:
          - python3-pyyaml
          - python3-pip
          - podman
          - buildah
          - libnotify

    - name: Install podenv
      command: python3 -m pip install --user .
      args:
        chdir: '{{ zuul.projects["github.com/podenv/podenv"].src_dir }}'
