---
- hosts: ci-node
  tasks:
    - name: Run test suite
      command: podenv --verbose
      args:
        chdir: '{{ zuul.projects["github.com/podenv/podenv"].src_dir }}'

    - name: Check README.md is not modified
      command: git diff README.md
      args:
        chdir: '{{ zuul.projects["github.com/podenv/podenv"].src_dir }}'
      register: _diff
      failed_when: _diff.stdout

    - name: Check list
      command: podenv --list

    - name: Check simple command
      command: podenv fedora cat /etc/os-release
