---
- hosts: ci-node
  tasks:
    - name: Install requirements
      become: yes
      package:
        name:
          - python3-pyyaml
          - python3-mypy
          - python3-flake8
          - make
          - bzip2
          - findutils

    - name: Run test
      command: make
      args:
        chdir: '{{ zuul.projects["github.com/podenv/podenv"].src_dir }}'
